[package]
name = "rslease"
version = "2.1.0-dev"
authors = ["Paul Blouët <paul@paulblouet.fr>"]
edition = "2018"

[dependencies]
anyhow = "1.0.28"
clap = "2.33.0"
fehler = "1.0.0"
regex = "1.3.7"
semver = "0.9.0"
